### PR TITLE
Ignore .idea folder

### PR DESCRIPTION
**Pull request by xepozz**

### CODE REVIEW

**Comment by Himself65** [comment]
Add it to your global gitignore, not here. Because we use different IDEs, either everyone here, or neither

https://stackoverflow.com/a/7335487

**Comment by xepozz** [comment]
It needs to apply by every contributor machines (even if the one has many) or just clone the repo and everything will work great.
The world has a few IDE's so that's why I don't see any problems to have 2 or 3 or even 10 line in `.gitignore` file that changes very rarely.
Anyway as you wish.

**Comment by Himself65** [comment]
You might be right. no bad for a few lines, could you please add `.vscode` also then I merge?

**Comment by xepozz** [comment]
Done

**Pull request merged**
