### PR TITLE
fix: inline icons from `@mui/icons-material`

### PR DESCRIPTION
**Pull request by rtritto**
## Changes:
- Remove `@mui/icons-material` dependency

- Create Icons with svg

Related #140

### CODE REVIEW

**Comment by pionxzh** [comment]
Thanks for the PR 👍 
Will it be better that use deep import to reduce the bundle size?
Like:
```diff
-import { Check as CheckIcon } from '@mui/icons-material'
+import CheckIcon from '@mui/icons-material/Check'
```

**Comment by rtritto** [comment]
As alternative, create a single Icons file to include all icons?

**Comment by rtritto** [comment]
@pionxzh changed https://github.com/TexteaInc/json-viewer/pull/147/commits/b276acd5a224ec87cb77f1f93c163c3caf6f620b

**Comment by pionxzh** [comment]
I just checked the bundle size of this PR, but it didn't bring down the total size 😢
We might need some other way to fix it.
Btw, I want to set up some bundle size checker to make developers aware of the size diff.

**Comment by rtritto** [comment]
Anyway this PR removes 1 dependency, can be merged

**Comment by rtritto** [comment]
@pionxzh rebased

**Comment by anthonyalayo** [comment]
I was analyzing why so many modules are being used for my next.js dev build, and I pointed to the fact that json-viewer uses icons-material. Could we give this a merge? That would be great!

**Comment by pionxzh** [comment]
Let's ship this. Thanks for your work @rtritto

**Review by pionxzh — APPROVED** [review]

**Comment by pionxzh** [comment]
@anthonyalayo May I know your setup? bundler and the config.
Please let me know if it gets improved in [v2.13.0](https://github.com/TexteaInc/json-viewer/releases/tag/json-viewer-v2.13.0) 🙏

**Comment by anthonyalayo** [comment]
Hey @pionxzh, thanks for the release! I took a while on the response as I was double checking all the numbers.

I'm playing with a next.js boilerplate with version 13.1.2.

Here's what the compile output looks like with:
1. `next dev`
2. `"@textea/json-viewer": "2.12.5"`
3. `outputFileTracing: true` and `output: 'standalone'` in `next.config.js`:

> compiled client and server successfully in 38.3s (12492 modules)

Notice the extremely large modules count and long build time (its basically an empty project). 
The next configuration above outputs a `.next/trace` which gives more details:

image

As you can see, there was a ton of hits from `@mui/icons`. I took a look in the package-lock.json to see that only `@textea/json-viewer` was using it.




Here's what the compile output looks like with:
1. `next dev`
2. `"@textea/json-viewer": "2.13.0"`
3. `outputFileTracing: true` and `output: 'standalone'` in `next.config.js`:

> event - compiled client and server successfully in 17.2s (1936 modules)

Much better! I can see that the 10K+ `@mui/icons` dependencies are gone:

image

With that being said, the dependency on `@mui/material` is still causing a lot of bloat:

image

That would probably take the module down to something reasonable. 

[MUI has a page dedicated to techniques ensuring it doesn't bloat builds](https://mui.com/material-ui/guides/minimizing-bundle-size/). 
Would applying that to your MUI components be possible?

**Comment by pionxzh** [comment]
@anthonyalayo You are right. I just checked the output and yes it didn't get transformed properly.

**Comment by anthonyalayo** [comment]
@pionxzh I made a PR for a fix, could you review it [here](https://github.com/TexteaInc/json-viewer/pull/168)?

**Pull request merged**
