### PR TITLE
[WIP] remove @textea/dev-kit from dependencies

### PR DESCRIPTION
**Pull request by forrestbao**
Arguments here https://github.com/TexteaInc/json-viewer/issues/133#issuecomment-1371984068 
Issue #133

### CODE REVIEW

**Comment by asafshen** [comment]
@forrestbao thanks for the quick fix! any estimation for when a new version of this package will be publish?

**Comment by forrestbao** [comment]
@asafshen we will bump the version soon. Thank you for your patience.

**Comment by pionxzh** [comment]
@asafshen [v2.12.5](https://github.com/TexteaInc/json-viewer/releases/tag/json-viewer-v2.12.5) has been released. 🚀

**Comment by asafshen** [comment]
@forrestbao @pionxzh thanks for the quick release! much appreciated

**Pull request merged**
