### PR TITLE
Mui treeshaking

### PR DESCRIPTION
**Pull request by ojemuyiwa**
useing webpack analyser all @mui import sizes should be reduced

### CODE REVIEW

**Comment by ojemuyiwa** [comment]
Sorry this is supposed to be for forked repo, i'm trying to reduce the material import sizes

**Comment by pionxzh** [comment]
#169 should have already fixed the problem?

**Comment by ojemuyiwa** [comment]
> #169 should have already fixed the problem?

Nope huge build with multiple modules included. 

Reduced changes in my forked repo in pink, this in violet.
Screenshot 2023-02-22 at 13 14 04
Screenshot 2023-02-22 at 13 19 14

Basically just did `Ctrl + Find` for `@mui/material` and replaced as suggested here [minimizing bundle size](https://mui.com/material-ui/guides/minimizing-bundle-size/)

**Comment by pionxzh** [comment]
Interesting. I see. I will verify the bundling size again recently.

**Comment by pionxzh** [comment]
Yo @ojemuyiwa bro... I realized that I never released #169, which should be why you still get a huge build. Not sure if you are willing to test again with [v2.14.0](https://github.com/TexteaInc/json-viewer/releases/tag/json-viewer-v2.14.0)?

**Comment by ojemuyiwa** [comment]
> Yo @ojemuyiwa bro... I realized that I never released #169, which should be why you still get a huge build. Not sure if you are willing to test again with [v2.14.0](https://github.com/TexteaInc/json-viewer/releases/tag/json-viewer-v2.14.0)?

For sure, I'll pull and test tomorrow morning and give you feedback. If you want the optimised code I can branch and fix for you here as well. 

Thanks and much appreciated 👍🏾

**Pull request closed without merging**
