### PR TITLE
Collapse empty objects and arrays

### PR DESCRIPTION
**Pull request by xepozz**

### CODE REVIEW

**Comment by xepozz** [comment]
image

it doesn't work well so I'll try to do better next time

**Comment by Himself65** [comment]
> image
> 
> it doesn't work well so I'll try to do better next time

it is because when precomponent and postcompoent are provided, the icons will be appended dynamically depending on `props.inspect`

**Comment by Himself65** [comment]
i suggest if the array or object is empty, always force inspect to false in the component

**Comment by Himself65** [comment]
```tsx
const ObjectType = (props) => {
  if (props.inspect === true && isEmpty(props.value)) {
    props.setInspect(false)
  }
}
```

**Comment by Himself65** [comment]
I tried. I think it's useless that force collapses an object or an array. It costs much for a small case for we need to check whether it's empty, length = 0, even if it's iteratorable.

I think just let it go because empty stuff with newlines it's not a big deal

**Pull request closed without merging**
